### ISSUE TITLE
Add Countries endpoint

### ISSUE THREAD

**Issue by pstorch** [RailwayStations/RSAPI#13]
Add an API endpoint for the list of supported countries. So the Android and iOS Apps don't need to connect to two different backends. 

Provide the timetable URL templates for each country and the needed query parameters (uic, IBNR or ds100).

**Comment by pstorch** [comment]
The current Drupal country endpoint:
https://railway-stations.org/laenderdaten.json

```
[
{
country: "Schweiz",
mail: "fotos@schweizer-bahnhoefe.ch",
twitter_tags: "@BahnhoefeCH, @android_oma, #BahnhofsfotoCH",
countryflag: "CH"
},
{
country: "Deutschland",
mail: "bahnhofsfotos@deutschlands-bahnhoefe.de",
twitter_tags: "@android_oma, #dbHackathon, #dbOpendata, #Bahnhofsfoto, @khgdrn",
countryflag: "DE"
}
]
```

Add Timetable URL Templates:
- DE: https://mobile.bahn.de/bin/mobil/bhftafel.exe/dox?bt=dep&max=10&rt=1&use_realtime_filter=1&start=yes&input=%s
- CH: http://fahrplan.sbb.ch/bin/stboard.exe/dn?input=%s&REQTrain_name=&boardType=dep&time=now&maxJourneys=20&selectDate=today&productsFilter=1111111111&start=yes

At the moment only the station title is inserted into `%s`, but we might need `UIC`, `IBNR` or `DS100`.

**Comment by androidoma** [comment]
FI: http://timetable-fi.railway-stations.org/index.php?stationshortcode=HKI
Parameter = stationShortCode from the json-baseurl
