### ISSUE TITLE
Neuer Bahnhof Münster-Mecklenbeck

### ISSUE THREAD

**Issue by androidoma** [RailwayStations/RSAPI#30]
https://www.openstreetmap.org/?mlat=51.9241&mlon=7.5794#map=14/51.9241/7.5794
Name: Münster-Mecklenbeck (#7813)
Adresse: Weseler Straße, 48151 Münster
Bahnhofsmanagement: Münster (Westf) (#56)
Regionalbereich: RB West (#4)
Ril100-Codes: EMEK
EVA-Nummern: undefined
Bundesland: Nordrhein-Westfalen
Aufgabenträger: Zweckverband Nahverkehr Westfalen-Lippe (NWL)
Fahrplanbüro: Bahnhofsmanagement Essen
Kategorie: 6

**Comment by khgdrn** [comment]
done
