### ISSUE TITLE
Fehler in Statistik (Anzahl Fotografen)

### ISSUE THREAD

**Issue by khgdrn** [RailwayStations/RSAPI#6]
Da ist ein Fehler in http://api.railway-stations.org/de/stats.txt.
Ist: photographers	131
Soll: photographers	137

siehe auch https://railway-stations.org/aktueller-stand.html

**Comment by pstorch** [comment]
Da sind dann wohl 6 Fotografen, die unter "Anonym" zusammengefasst wurden.
Bis auf unseren einen Geheimagenten kann ich die in der API nicht unterscheiden.
@androidoma vielleicht müssten wir doch über eine Fotografen ID nachdenken, die wir anstelle "Anonym" setzen. Damit wir die auseinander halten können.

**Comment by pstorch** [comment]
Die Statistik ist Länderabhängig ohne Ländercode stimmt die Anzahl der Fotografen: http://api.railway-stations.org/stats.txt
